services:
  api:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Allows the container to reach Ollama running on the host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  worker:
    build: .
    command: python -m app.pipeline.worker
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  db:
    container_name: citizen_link_docai_db
    image: postgres:16-alpine
    restart: unless-stopped
    # ports:
    #   - '5432:5432'
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # Best practice: ensures the DB uses the exact volume path
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
      container_name: citizen_link_docai_redis
      image: redis:7-alpine
      restart: unless-stopped
      command: >
        sh -c "
          echo 'user default off' > /tmp/redis.acl &&
          echo \"user $${REDIS_USERNAME} on >$${REDIS_PASSWORD} ~* &* +@all\" >> /tmp/redis.acl &&
          redis-server --aclfile /tmp/redis.acl
        "
      # ports:
      #   - '6379:6379'
      env_file:
        - .env
      environment:
        - REDIS_USERNAME=${REDIS_USERNAME}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
      volumes:
        - redis_data:/data
      healthcheck:
        test: ['CMD-SHELL', 'redis-cli -u redis://$${REDIS_USERNAME}:$${REDIS_PASSWORD}@localhost:6379 ping | grep -q PONG']
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 15s

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
